apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-minikube-replicaset
  labels:
    app: hello-minikube
spec:
  replicas: 1
  template:
    metadata:
      name: hello-minikube
      # Adding a label to the pod template here
      labels:
        app: hello-minikube
    spec:
      containers:
        - name: hello-minikube
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
  # The selector will match all pods having label hello-minikube, bringing them in under the supervision of this replicaset
  selector:
    matchLabels:
      app: hello-minikube
